name: Feature Request
description: Suggest an idea or improvement for Stream Havoc.
title: "[Feature]: "
labels:
  - type:feature
body:
  - type: textarea
    id: request
    attributes:
      label: Feature request
      value: |
        Give your feedback, or explain the feature you would like to see added to Stream Havoc
    validations:
      required: true
